[package]
name = "twitch-irc"
version = "0.1.0"
authors = ["Ruben Anders <ruben.anders@robotty.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
async-trait = "0.1.22"
thiserror = "1.0.9"
futures = "0.3.1"
smallvec = "1.1.0"
log = "0.4.8"
derivative = "2.1.1"
enum_dispatch = "0.3.1"
tokio = { version = "0.2.21", features = ["rt-core", "time", "sync", "macros"] }
tokio-util = { version = "0.3.1", features = ["codec"], optional = true }
bytes = { version = "0.5.3", optional = true }
tungstenite = { version = "0.11.0", optional = true }
async-tungstenite = { version = "0.6.0", features = ["tokio-runtime", "tokio-native-tls"], optional = true }
tokio-native-tls = { version = "0.1.0", optional = true }
native-tls = { version = "0.2.4", optional = true }
reqwest = { version = "0.10.6", features= ["json"], optional = true }
serde = { version = "1.0.114", features = ["derive"], optional = true }
chrono = { version = "0.4.13", features = ["serde"], optional = true }

[dev-dependencies]
maplit = "1.0.2"
env_logger = "0.7.1"

[lib]
name = "twitch_irc"
path = "src/lib.rs"

[[example]]
name = "simple_listener"
required-features = ["transport-tcp"]

[features]
default = ["transport-tcp"]
refreshing-token = ["reqwest", "serde", "chrono"]
transport-tcp = ["bytes", "tokio-native-tls", "native-tls", "tokio/dns", "tokio/tcp", "tokio/io-util", "tokio-util"]
transport-wss = ["tungstenite", "async-tungstenite", "tokio-native-tls", "native-tls"]
