[package]
name = "twitch-irc"
description = "Connect to Twitch chat from a Rust application."
license = "MIT"
version = "0.2.1"
authors = ["Ruben Anders <ruben.anders@robotty.de>"]
repository = "https://github.com/robotty/twitch-irc-rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# https://docs.rs/about/metadata
[package.metadata.docs.rs]
all-features = true

[dependencies]
itertools = "0.9.0"
async-trait = "0.1.42"
thiserror = "1.0.22"
futures = "0.3.8"
log = "0.4.8"
enum_dispatch = "0.3.4"
chrono = "0.4.19"
tokio = { version = "0.2.22", features = ["rt-core", "time", "sync", "macros", "stream"] }
tokio-util = { version = "0.3.1", features = ["codec"], optional = true }
bytes = { version = "0.5.3", optional = true }
tungstenite = { version = "0.11.1", optional = true }
async-tungstenite = { version = "0.10.0", features = ["tokio-runtime", "tokio-native-tls"], optional = true }
tokio-native-tls = { version = "0.1.0", optional = true }
native-tls = { version = "0.2.6", optional = true }
reqwest = { version = "0.10.9", features= ["json"], optional = true }
serde = { version = "1.0.117", features = ["derive"], optional = true }
metrics = { version = "0.12.1", optional = true }
smallvec = "1.5.0"

[dev-dependencies]
maplit = "1.0.2"
env_logger = "0.8.2"

[lib]
name = "twitch_irc"
path = "src/lib.rs"

[[example]]
name = "simple_listener"
required-features = ["transport-tcp"]

[features]
default = ["transport-tcp"]
refreshing-token = ["reqwest", "serde", "chrono/serde"]
transport-tcp = ["bytes", "tokio-native-tls", "native-tls", "tokio/dns", "tokio/tcp", "tokio/io-util", "tokio-util"]
transport-wss = ["tungstenite", "async-tungstenite", "tokio-native-tls", "native-tls"]
metrics-collection = ["metrics"]
