name: Audit Rust dependencies

on:
  push:
  pull_request:
  schedule:
    - cron: '30 3 * * *' # At 3:30 every day

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
