name: Rust

on: [push, pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: install rustfmt
      run: rustup component add rustfmt
    - name: Check format
      run: cargo fmt -- --check
  test:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.6
      with:
        path: |
          /usr/local/cargo/registry
          /usr/local/cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-test
    - name: Run tests (only default features)
      run: cargo test
    - name: Run tests (all tests enabled)
      run: cargo test --features "refreshing-token"
  build:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.6
      with:
        path: |
          /usr/local/cargo/registry
          /usr/local/cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-build
    - name: Check (default features)
      run: cargo check --examples --lib
    - name: Check (native-tls)
      run: cargo check --no-default-features --features "transport-tcp transport-tcp-native-tls transport-ws transport-ws-native-tls refreshing-token metrics-collection with-serde" --lib --examples
    - name: Check (rustls-native-roots)
      run: cargo check --no-default-features --features "transport-tcp transport-tcp-rustls-native-roots transport-ws transport-ws-rustls-native-roots refreshing-token metrics-collection with-serde" --lib --examples
    - name: Check (rustls-webpki-roots)
      run: cargo check --no-default-features --features "transport-tcp transport-tcp-rustls-webpki-roots transport-ws transport-ws-rustls-webpki-roots refreshing-token metrics-collection with-serde" --lib --examples
    - name: Check (no default features)
      run: cargo check --no-default-features --lib
    - name: Check (default features with serde)
      run: cargo check --features "with-serde" --lib
  docs:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.6
      with:
        path: |
          /usr/local/cargo/registry
          /usr/local/cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-docs
    - name: Build documentation
      # If updating this make sure to update Cargo.toml ([package.metadata.docs.rs]) too
      run: cargo doc --no-deps --no-default-features --features "refreshing-token transport-tcp transport-tcp-rustls-webpki-roots transport-ws transport-ws-rustls-webpki-roots metrics-collection with-serde"
    - uses: actions/upload-artifact@v2
      with:
        name: docs
        path: target/doc/
